# BUILD.bazel
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@bazel_ros2_rules//ros2:ros_cc.bzl", "ros_cc_binary", "ros_cc_test")

cc_library(
    name = "ese_lib",
    srcs = ["src/ese.cpp"],
    hdrs = ["include/ese.hpp"],
    includes = ["include"],
    deps = [
        #"@ros2_rclcpp//:rclcpp",
        #"@ros2_common_interfaces//:cpp_std_msgs",
        "@ros2//:rclcpp",
    ],
)

ros_cc_binary(
    name = "ese_node", # Changed name to be more descriptive
    srcs = ["src/main.cpp"],
    deps = [
        ":ese_lib", # Depends on our new library
        "@ros2//:rclcpp",
    ],
)

ros_cc_test(
    name = "ese_test",
    size = "small",
    srcs = ["test/ese_test.cpp"],
    # The test needs to link against GTest, ROS, and our talker library
    deps = [
        ":ese_lib",
        "@ros2//:rclcpp",
        "@googletest//:gtest_main", # This brings in GTest
    ],
)