# tools/coverage/BUILD.bazel
#load("@bazel_tools//tools/cpp:cc_toolchain.bzl", "cc_toolchain")
#load("@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl", "tool_path")

package(default_visibility = ["//visibility:public"])

load(":defs.bzl", "etharialle_cc_toolchain_config")

etharialle_cc_toolchain_config(
    name = "etharialle_toolchain_config_impl"
)

# This creates the actual toolchain target that Bazel can use.
cc_toolchain(
    name = "cc_toolchain_impl",
    toolchain_identifier = "coverage-clang",
    toolchain_config = ":etharialle_toolchain_config_impl",
    # Point to the wrapper script and other files needed by the toolchain.
    all_files = ":wrapper",
    compiler_files = ":wrapper",
    dwp_files = ":empty",
    linker_files = ":wrapper",
    objcopy_files = ":empty",
    strip_files = ":empty",
    supports_param_files = 1,
)

# This defines the configuration for our Clang toolchain,
# specifically overriding the gcov tool path.
toolchain(
    name = "etharialle_coverage",
    #compiler = "clang",
    #cpu = "k8", # A common default, adjust if needed for your architecture
    toolchain = ":cc_toolchain_impl", #this should match the name in the cc_toolchain() function
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
    exec_compatible_with = [],
    target_compatible_with = [],
    #cxx_flag = ["-std=c++17"],
    #linker_flag = ["-lm"],
    #toolchain_identifier = "clang-coverage-toolchain",
    #tool_path = [
    #    # This is the key change: we point the 'gcov' tool to our wrapper script.
    #    tool_path(name = "gcov", path = "llvm-gcov-wrapper.sh"),
    #    # Define other tools to make the toolchain complete.
    #    # Adjust these paths if clang/ld are not in your system's default PATH.
    #    tool_path(name = "ar", path = "/usr/bin/ar"),
    #    tool_path(name = "cpp", path = "/usr/bin/clang-c++"),
    #    tool_path(name = "gcc", path = "/usr/bin/clang"),
    #    tool_path(name = "ld", path = "/usr/bin/ld"),
    #    tool_path(name = "nm", path = "/usr/bin/nm"),
    #    tool_path(name = "objcopy", path = "/usr/bin/objcopy"),
    #    tool_path(name = "objdump", path = "/usr/bin/objdump"),
    #    tool_path(name = "strip", path = "/usr/bin/strip"),
    #],
)



# A filegroup to bundle the wrapper script for the toolchain.
filegroup(
    name = "wrapper",
    srcs = ["llvm-gcov-wrapper.sh"],
)

# An empty filegroup for toolchain attributes that we don't need.
filegroup(name = "empty")